### ISSUE TITLE
可否选择获取amazon.cn高清晰封面图？

### ISSUE THREAD

**Issue by heeloo** [fated/calibre_amazon_cn#1]
http://z2-ec2.images-amazon.com/images/P/**********.01.MAIN._SCRM_.jpg
以上是大图获取地址，**********应该以ASIN（例：B00Q4EJQVA）代替.
有的书籍没有高清封面图，则仍然使用普通封面图.

**Comment by fated** [comment]
@heeloo  谢谢提供高清封面图地址! 代码已添加, 默认使用高清图, 切换高清封面和标清封面的选项在之后的更新里会添加.  
目前还有个小bug就是, 现在是用urllib发送地址请求通过服务器的http返回代码来判断图片链接是否有效, 但是貌似Amazon对不存在的图片(比如随便填的ASIN码)也会返回200成功代码, 解决方法我再想想. 不过实际应用中会影响到正常使用的几率貌似很小.
